### ISSUE TITLE
W7 error

### ISSUE THREAD

**Issue by oligu** [haknode/AtomPortable#1]
I've downloaded and installed the app with the portableApps platform.
When launching Atom from the portableApps platform, I get the error:
![atom_w7_error](https://cloud.githubusercontent.com/assets/3225652/15495229/1c250a30-218f-11e6-8282-d9da8661357c.PNG)
and Atom does not open.
However, I'm running on a Windows 7 Enterprise SP1.
When I manually launch the AtomPortable.exe, it opens without error.

**Comment by haknode** [comment]
could you please try to remove the line "MinOS=7" from the file AtomPortable\App\AppInfo\Launcher\AtomPortable.ini
i cant test it myself

**Comment by oligu** [comment]
Now I see the splash screen and then
![atom_stoppedworking](https://cloud.githubusercontent.com/assets/3225652/15544579/88110a40-2299-11e6-9075-bb30b63ef606.PNG)
Then full details are
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	atom.exe
  Application Version:	0.36.8.0
  Application Timestamp:	56c6e405
  Fault Module Name:	atom.exe
  Fault Module Version:	0.36.8.0
  Fault Module Timestamp:	56c6e405
  Exception Code:	80000003
  Exception Offset:	001fcf41
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	2055
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

Still this only happens when I launch it from the portableApps application. Executing the AtomPortable.exe directly works fine.
